insert into RESTAURANTE (NOMBRE_RESTAURANTE,UBI_RESTAURANTE,GER_RESTAURANTE,TELF_RESTAURANTE)
values ('Restaurante Gemelos', 'Manta Central', 'Carmen Sornoza', '0934746588');
insert into RESTAURANTE (NOMBRE_RESTAURANTE,UBI_RESTAURANTE,GER_RESTAURANTE,TELF_RESTAURANTE)
values ('Restaurante JuanCa', 'Flavio Reyes', 'Jennifer Mantuano', '0975778888');
insert into RESTAURANTE (NOMBRE_RESTAURANTE,UBI_RESTAURANTE,GER_RESTAURANTE,TELF_RESTAURANTE)
values ('Restaurante ElDanJ', 'Barrio San Agustin', 'Maria Camila Zambrano', '0845638264');

insert into CHEF (ID_RESTAURANTE,CI_CHEF,NOMBRE_CHEF,APELLIDO_CHEF,TELF_CHEF,DIRECCION_CHEF)
values(1, '1350696394', 'Mauricio', 'Carvajal', '0983364542', 'San juan');
insert into CHEF (ID_RESTAURANTE,CI_CHEF,NOMBRE_CHEF,APELLIDO_CHEF,TELF_CHEF,DIRECCION_CHEF)
values(2, '0037467589', 'Bernardo', 'Delgado', '0965457732', 'Santa Marta');
insert into CHEF (ID_RESTAURANTE,CI_CHEF,NOMBRE_CHEF,APELLIDO_CHEF,TELF_CHEF,DIRECCION_CHEF)
values(3, '1736485893', 'Juan Carlos', 'Cedeño', '0873356278', 'San Pablo');
insert into CHEF (ID_RESTAURANTE,CI_CHEF,NOMBRE_CHEF,APELLIDO_CHEF,TELF_CHEF,DIRECCION_CHEF)
values(2, '1736484027', 'Santa', 'Dueñas', '0973635782', 'Altagracia');
insert into CHEF (ID_RESTAURANTE,CI_CHEF,NOMBRE_CHEF,APELLIDO_CHEF,TELF_CHEF,DIRECCION_CHEF)
values(1, '0003476472', 'Gabriela', 'Mendoza', '0983334542', 'La Pradera');

insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Carlos', 'Alcivar', '1673949038', '0983424523', 'carlos@gmail.com');
insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Juan', 'Altasig', '1350696397', '0983424523', 'juans@gmail.com');
insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Karla', 'Cheme', '1315868057', '0983424523', 'karla@gmail.com');
insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Dayana', 'Alvarez', '1307735769', '0983424523', 'dayana@gmail.com');
insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Stefanya', 'Delgado', '1350696395', '0983424523', 'stefanya@gmail.com');
insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Yuletzi', 'Cevallos', '1307735028', '0983424523', 'yuetzi@gmail.com');
insert into CLIENTE (NOMBRE_CLIENTE,APELLIDO_CLIENTE,CI_CLIENTE,TELF_CLIENTE,CORREO_CLIENTE)
values('Josue', 'Santander', '1317452829', '0983424523', 'josue@gmail.com');

insert into MENU (NOMBRE_MENU,PRECIO_VENTA_MENU,COSTO_MENU,DESCRIPCION_MENU,CANTIDAD_VENDIDA_MENU)
values('Menu completo', 8.50, 5.00, 'Este menu es completo y la decision de lo que contiene es del cliente',2);
insert into MENU (NOMBRE_MENU,PRECIO_VENTA_MENU,COSTO_MENU,DESCRIPCION_MENU,CANTIDAD_VENDIDA_MENU)
values('Burguer', 6.50, 3.50, 'Esta es una hamburguesa contine de todo',2);
insert into MENU (NOMBRE_MENU,PRECIO_VENTA_MENU,COSTO_MENU,DESCRIPCION_MENU,CANTIDAD_VENDIDA_MENU)
values('Grilleth', 7.50, 5.00, 'Es establecido por el cliente',2);
insert into MENU (NOMBRE_MENU,PRECIO_VENTA_MENU,COSTO_MENU,DESCRIPCION_MENU,CANTIDAD_VENDIDA_MENU)
values('Cooked',5.60, 3.00, 'Este menu es el mas indicado y mas economico',2);


insert into MATERIAL (ID_RESTAURANTE,NOMBRE_MATERIAL,CANTIDAD_MATERIAL,FECHA_MATERIAL)
values(1,  'Pechugas de pollo', 54, '15/08/2021');
insert into MATERIAL (ID_RESTAURANTE,NOMBRE_MATERIAL,CANTIDAD_MATERIAL,FECHA_MATERIAL) 
values(1,  'carne molida en libras', 154, '25/10/2021');
insert into MATERIAL (ID_RESTAURANTE,NOMBRE_MATERIAL,CANTIDAD_MATERIAL,FECHA_MATERIAL)
values(2,  'arroz por libra', 45, '16/06/2020');
insert into MATERIAL (ID_RESTAURANTE,NOMBRE_MATERIAL,CANTIDAD_MATERIAL,FECHA_MATERIAL)
values(2,  'verduras', 78, '27/08/2020');
insert into MATERIAL (ID_RESTAURANTE,NOMBRE_MATERIAL,CANTIDAD_MATERIAL,FECHA_MATERIAL)
values(3,  'Papa en libras', 132, '05/11/2021');

insert into MESERO (ID_RESTAURANTE,CI_MESERO,NOMBRE_MESERO,APELLIDO_MESERO,TELF_MESERO,DIRECCION_MESERO)
values(1,  '1350745362', 'Carolina', 'Santana',  '0937474853', 'Barrio Lss Esteros');
insert into MESERO (ID_RESTAURANTE,CI_MESERO,NOMBRE_MESERO,APELLIDO_MESERO,TELF_MESERO,DIRECCION_MESERO)
values(2,  '0073646272', 'Angelica', 'Robles',   '0936371721', 'Barrio Santa Marta');
insert into MESERO (ID_RESTAURANTE,CI_MESERO,NOMBRE_MESERO,APELLIDO_MESERO,TELF_MESERO,DIRECCION_MESERO)
values(3,  '1307565633', 'Efrain', 'Ruales',     '0964738181', 'Ciudadela Universitaria');
insert into MESERO (ID_RESTAURANTE,CI_MESERO,NOMBRE_MESERO,APELLIDO_MESERO,TELF_MESERO,DIRECCION_MESERO)
values(1,  '1736567372', 'Jhon', 'Cevallos',     '0909064572', 'Montecristi');
insert into MESERO (ID_RESTAURANTE,CI_MESERO,NOMBRE_MESERO,APELLIDO_MESERO,TELF_MESERO,DIRECCION_MESERO)
values(2,  '1308456474', 'Catalina', 'Santander','0989836234', 'La proaño');
insert into MESERO (ID_RESTAURANTE,CI_MESERO,NOMBRE_MESERO,APELLIDO_MESERO,TELF_MESERO,DIRECCION_MESERO)
values(3,  '1625373844', 'Carolina', 'Gaitan',   '0938621313', 'La Aurora');

insert into MESA ( ID_RESTAURANTE, NUM_MESA, CAPACIDAD_MESA, ESTADO_MESA, DESCRIPCION_MESA)
values(1, 1, 4,'Libre','Mesa para 4 personas y un adicional para niño');
insert into MESA ( ID_RESTAURANTE, NUM_MESA, CAPACIDAD_MESA, ESTADO_MESA, DESCRIPCION_MESA) 
values(2, 1, 3,'Libre','Mesa en terraza');
insert into MESA ( ID_RESTAURANTE, NUM_MESA, CAPACIDAD_MESA, ESTADO_MESA, DESCRIPCION_MESA)
values(3, 1, 4,'Libre','Mesa econónimo');
insert into MESA ( ID_RESTAURANTE, NUM_MESA, CAPACIDAD_MESA, ESTADO_MESA, DESCRIPCION_MESA) 
values(1, 2, 6,'Libre','Mesa cerca de la cocina');
insert into MESA ( ID_RESTAURANTE, NUM_MESA, CAPACIDAD_MESA, ESTADO_MESA, DESCRIPCION_MESA)
values(2, 2,12,'Libre','Mesa con vista a la ventana');

insert into ATENCION ( ID_MESERO ,ID_MESA ,FECHA_ATENCION,HORA_ATENCION)
values(1, 1,'01/01/2022','Desde las 15:00H hasta las 17:00H');
